[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
remappings = [
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@solmate=lib/solmate/src/",
]

[profile.sepolia]
eth_rpc_url = "${RPC_URL_ETH}"
verify = true

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${RPC_URL_ETH}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
